update Github actions - temporary skip ghcr.io push

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -146,10 +146,10 @@ jobs:
 
       - name: Check if secrets are available
         run: |
-          if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then
-            echo "Repository secret is missing: GHCR_TOKEN "
-            exit 1
-          fi
+          # if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then
+            # echo "Repository secret is missing: GHCR_TOKEN "
+            # exit 1
+          # fi
           if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
             echo "Repository variable is missing: DOCKERHUB_USERNAME "
             exit 1
@@ -193,13 +193,13 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       
       # https://github.com/settings/tokens/new?scopes=write:packages
-      - name: Login to GitHub Container Registry
-        if: ${{ inputs.push_image }}
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GHCR_TOKEN }}
+      # - name: Login to GitHub Container Registry
+      #   if: ${{ inputs.push_image }}
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.repository_owner }}
+      #     password: ${{ secrets.GHCR_TOKEN }}
 
       - name: Build and push Docker image
         uses: docker/build-push-action@v6
@@ -214,7 +214,6 @@ jobs:
           cache-to: type=gha,scope=${{ github.ref_name }},mode=max
           tags: |
             ${{ env.DOCKER_FULL_IMAGE }}
-            ghcr.io/${{ env.DOCKER_FULL_IMAGE }}
           build-args: |
             GO_VERSION=${{ env.GO_VERSION }}
 
@@ -275,6 +274,6 @@ jobs:
           docker image ls >> $GITHUB_STEP_SUMMARY
           echo "#### Docker full images:" >> $GITHUB_STEP_SUMMARY
           echo "-  _**${DOCKER_FULL_IMAGE}**_" >> $GITHUB_STEP_SUMMARY
-          echo "-  _**ghcr.io/${DOCKER_FULL_IMAGE}**_" >> $GITHUB_STEP_SUMMARY
+          ### echo "-  _**ghcr.io/${DOCKER_FULL_IMAGE}**_" >> $GITHUB_STEP_SUMMARY
           echo "#" >> $GITHUB_STEP_SUMMARY
           echo '#### 🧪 Binary was build and attached to this workflow for download.' >> $GITHUB_STEP_SUMMARY
